### ISSUE TITLE
Missing 'MGnify_EC.m8' in EC_mlp.py?

### ISSUE THREAD

**Issue by Andy-B-123** [y-hwang/gLM#5]
Hi, thank you for providing this repository! 

I've been able to follow the example data workflow and am looking at generating enzyme class predictions for the example proteins. I tried running both:
`python EC_mlp.py save inference/results/ plm`
and 
`python EC_mlp.py save inference/results/ plmglm`

And am getting the same error after running both:
`FileNotFoundError: [Errno 2] No such file or directory: 'MGnify_EC.m8'`

I believe in line 327 it's looking for that file in the current path but instead this could be provided as an additional commandline argument? Is there is a link to that specific file available somewhere? 

Also, apologies for the naive question, but could I check the usage for this?

```
# usage: python EC_mlp.py <save/split/train> <data_path> <plm/plmglm> 
# step 1: python EC_mlp.py save inference/results/ plm or python EC_mlp.py save inference/results/ plmglm
# step 2: python EC_mlp.py split EC_dat_mlp.plm.pkl plm or python EC_mlp.py split EC_dat_mlp.plmglm.pkl plmglm 
# step 3: python EC_mlp.py train train_split.plm.pkl plm or python EC_mlp.py split train_split.plmglm.pkl plmglm 
```
Is the plm the output from the pLM embedding and the plmglm the output from the gLM embedding? And this needs to run both split and train as this predicts enzyme classes using some kind of machine learning approach?

Thanks!

**Comment by Andy-B-123** [comment]
Hi, just hoping to bump this, hoping to assess this for my dataset but as far as I can tell I can't get EC information for this program without this file?

**Comment by y-hwang** [comment]
Hello, [Here](https://drive.google.com/drive/folders/1EaTrHIF0KzAGy244dEp7rcRT5uaxViid?usp=sharing) is the link to the file!

**Comment by Andy-B-123** [comment]
Thank you! I'm still struggling to find information on how to actually get the EC predictions for the test data but I'll close this issue as the file is now available!

**Comment by rhinempi** [comment]
> Thank you! I'm still struggling to find information on how to actually get the EC predictions for the test data but I'll close this issue as the file is now available!

Hi @Andy-B-123, I have the same question, did you figure out how to get the EC predictions? In the EC_mlp.py script, it does not seem to use any glm embeddings from the test data.

Thanks

**Comment by y-hwang** [comment]
Hi there, 
EC_mlp.py script is used to compare EC prediction performance of representations (e.g. ESM vs gLM). To predict the EC numbers of your own seqs/embeddings, you can train the predictor using EC_mlp.py, and run the trained predictor on the user defined set of embeddings.

**Comment by rhinempi** [comment]
Hi @y-hwang ,

thank you very much for your prompt answer. 

Maybe you could help me with my humble understanding here:
1), I should use my own seqs to firstly get the EC alignment/annotation same as the MGnify_EC.m8 -> myOWN_EC.m8
2), I should get the gLM embeddings of my own seqs and context and inference result -> data/test_results/results/myOWN.batch.pkl.glm.embs.pkl
3), using EC_mlp.py, here I start to be confused:
   #### step 1: python EC_mlp.py save inference/results/ plm or python EC_mlp.py save inference/results/ plmglm

In this step, save, EC_mlp.py reads files in the directory inference/results/ , and greps for files start with "train", My question is, where do I get these "train" files? 

It seem to me the gLM embedding of my own seqs and context are not used here. 

Lastly, "you can train the predictor using EC_mlp.py, and run the trained predictor on the user defined set of embeddings." 
I assume "train the predictor" is the :
#### step3: python EC_mlp.py train train_split.plm.pkl plm or python EC_mlp.py split (typo? train) train_split.plmglm.pkl plmglm 
then "run the trained predictor", how could I run the trained predictor?


Sorry for the long question, this part i can only interpret from the script, that's why I got confused.

Thanks

**Comment by y-hwang** [comment]
Hi @rhinempi, 
to train the predictor using EC_mlp.py you should run inference on all MGPY sequences (from MGnify) to get the glm or plm embeddings and save to inference/results/. 

then run python EC_mlp.py save inference/results/ plm ( you can also do plmglm by stacking esm embeddings with glm embeddings) map EC numbers to MGPY
then run EC_mlp.py split EC_dat_mlp.plm.pkl plm to split train and validations sets (useful for making sure your predictor is not overfitting)
then run python EC_mlp.py train train_split.plm.pkl plm, at this point you can save the trained model in the python code with torch.save() and load it for inferring on your own set of embeddings. 

This python code was meant for comparing performance of plm and glm representations for EC prediction task in the manuscript and wasn't designed for inferring additional sequences, so apologies for the complexity here.

**Comment by rhinempi** [comment]
Hi @y-hwang ,

thanks, that clears a lot. I just have one last question regarding the last step after torch.save():
 "and load it for inferring on your own set of embeddings."
In the paper, it mentioned that it uses Linear probing to predict the EC classes. Is this tool available or did I misunderstood something?

Thanks again.
